build: switch from buster to bookworm to Docker containers
Running with `buster` in CI gives us this error:
```
ERROR: failed to solve: golang:1.21.0-buster: docker.io/library/golang:1.21.0-buster: not found
```

So looks like the buster container is no longer being officially built.
So we'll switch to bookworm for now.